[build]
functions = ".netlify/functions"
command = "cd .netlify/functions/save-car-path; npm install"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"